# Generated by Django 4.2.10 on 2024-03-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_itemdata_origin_alter_item_group_alter_itemdata_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idatas', to='list.item'),
        ),
    ]
